// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addressbook.proto

package addressbook

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}

var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}

func (Person_PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{0, 0}
}

type Person struct {
	FirstName            string                `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string                `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phones               []*Person_PhoneNumber `protobuf:"bytes,4,rep,name=phones,proto3" json:"phones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Person) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Person) GetPhones() []*Person_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

type Person_PhoneNumber struct {
	Number               string           `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 Person_PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=addressbook.Person_PhoneType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Person_PhoneNumber) Reset()         { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()    {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{0, 0}
}

func (m *Person_PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person_PhoneNumber.Unmarshal(m, b)
}
func (m *Person_PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *Person_PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person_PhoneNumber.Merge(m, src)
}
func (m *Person_PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_Person_PhoneNumber.Size(m)
}
func (m *Person_PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_Person_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_Person_PhoneNumber proto.InternalMessageInfo

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil {
		return m.Type
	}
	return Person_MOBILE
}

type AddPersonResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPersonResponse) Reset()         { *m = AddPersonResponse{} }
func (m *AddPersonResponse) String() string { return proto.CompactTextString(m) }
func (*AddPersonResponse) ProtoMessage()    {}
func (*AddPersonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{1}
}

func (m *AddPersonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPersonResponse.Unmarshal(m, b)
}
func (m *AddPersonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPersonResponse.Marshal(b, m, deterministic)
}
func (m *AddPersonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPersonResponse.Merge(m, src)
}
func (m *AddPersonResponse) XXX_Size() int {
	return xxx_messageInfo_AddPersonResponse.Size(m)
}
func (m *AddPersonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPersonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPersonResponse proto.InternalMessageInfo

func (m *AddPersonResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AddPersonResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ListAddressBookRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAddressBookRequest) Reset()         { *m = ListAddressBookRequest{} }
func (m *ListAddressBookRequest) String() string { return proto.CompactTextString(m) }
func (*ListAddressBookRequest) ProtoMessage()    {}
func (*ListAddressBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{2}
}

func (m *ListAddressBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAddressBookRequest.Unmarshal(m, b)
}
func (m *ListAddressBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAddressBookRequest.Marshal(b, m, deterministic)
}
func (m *ListAddressBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAddressBookRequest.Merge(m, src)
}
func (m *ListAddressBookRequest) XXX_Size() int {
	return xxx_messageInfo_ListAddressBookRequest.Size(m)
}
func (m *ListAddressBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAddressBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAddressBookRequest proto.InternalMessageInfo

type ListAddressBookResponse struct {
	Success              bool      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Persons              []*Person `protobuf:"bytes,2,rep,name=persons,proto3" json:"persons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListAddressBookResponse) Reset()         { *m = ListAddressBookResponse{} }
func (m *ListAddressBookResponse) String() string { return proto.CompactTextString(m) }
func (*ListAddressBookResponse) ProtoMessage()    {}
func (*ListAddressBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{3}
}

func (m *ListAddressBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAddressBookResponse.Unmarshal(m, b)
}
func (m *ListAddressBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAddressBookResponse.Marshal(b, m, deterministic)
}
func (m *ListAddressBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAddressBookResponse.Merge(m, src)
}
func (m *ListAddressBookResponse) XXX_Size() int {
	return xxx_messageInfo_ListAddressBookResponse.Size(m)
}
func (m *ListAddressBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAddressBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAddressBookResponse proto.InternalMessageInfo

func (m *ListAddressBookResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListAddressBookResponse) GetPersons() []*Person {
	if m != nil {
		return m.Persons
	}
	return nil
}

func init() {
	proto.RegisterEnum("addressbook.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
	proto.RegisterType((*Person)(nil), "addressbook.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "addressbook.Person.PhoneNumber")
	proto.RegisterType((*AddPersonResponse)(nil), "addressbook.AddPersonResponse")
	proto.RegisterType((*ListAddressBookRequest)(nil), "addressbook.ListAddressBookRequest")
	proto.RegisterType((*ListAddressBookResponse)(nil), "addressbook.ListAddressBookResponse")
}

func init() { proto.RegisterFile("addressbook.proto", fileDescriptor_1eb1a68c9dd6d429) }

var fileDescriptor_1eb1a68c9dd6d429 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0xb1, 0xa4, 0xcd, 0x04, 0xb4, 0x5d, 0xa1, 0x86, 0x4a, 0xb5, 0x44, 0x0f, 0x05, 0xb1,
	0x60, 0x3d, 0x78, 0xb5, 0x85, 0xa2, 0x62, 0xbf, 0x58, 0x04, 0x3d, 0x08, 0x92, 0x34, 0xa3, 0x96,
	0x9a, 0x6c, 0xcc, 0xa4, 0x87, 0xde, 0xfd, 0x3b, 0xfe, 0x47, 0xc9, 0xa6, 0x29, 0xa9, 0x8d, 0x7a,
	0xdb, 0x79, 0xef, 0xcd, 0xbc, 0x37, 0xc3, 0x42, 0xc5, 0x76, 0xdd, 0x10, 0x89, 0x1c, 0x21, 0x66,
	0xad, 0x20, 0x14, 0x91, 0x60, 0x46, 0x06, 0xb2, 0x3e, 0x55, 0xd0, 0xc6, 0x18, 0x92, 0xf0, 0x59,
	0x1d, 0xe0, 0x65, 0x1a, 0x52, 0xf4, 0xec, 0xdb, 0x1e, 0x9a, 0x4a, 0x43, 0x69, 0xea, 0x5c, 0x97,
	0xc8, 0xd0, 0xf6, 0x90, 0x1d, 0x80, 0xfe, 0x6e, 0xa7, 0xac, 0x2a, 0xd9, 0x52, 0x0c, 0x48, 0xf2,
	0x12, 0xb4, 0xe0, 0x4d, 0xf8, 0x48, 0x66, 0xa1, 0xb1, 0xdd, 0x34, 0xda, 0x47, 0xad, 0xac, 0x6f,
	0x62, 0xd0, 0x1a, 0xc7, 0x8a, 0xe1, 0xdc, 0x73, 0x30, 0xe4, 0x4b, 0x79, 0xed, 0x11, 0x8c, 0x0c,
	0xcc, 0xaa, 0xa0, 0xf9, 0xf2, 0xb5, 0xf4, 0x5f, 0x56, 0xec, 0x1c, 0x0a, 0xd1, 0x22, 0x48, 0x7c,
	0x77, 0xda, 0xf5, 0x5f, 0xa7, 0xdf, 0x2f, 0x02, 0xe4, 0x52, 0x6a, 0x9d, 0x82, 0xbe, 0x82, 0x18,
	0x80, 0x36, 0x18, 0x75, 0x6f, 0xfb, 0xbd, 0xf2, 0x16, 0x2b, 0x41, 0xe1, 0x66, 0x34, 0xe8, 0x95,
	0x95, 0xf8, 0xf5, 0x30, 0xe2, 0x77, 0x65, 0xd5, 0xba, 0x86, 0x4a, 0xc7, 0x75, 0x93, 0x49, 0x1c,
	0x29, 0x10, 0x3e, 0x21, 0x33, 0xa1, 0x48, 0xf3, 0xc9, 0x04, 0x89, 0x64, 0x9a, 0x12, 0x4f, 0xcb,
	0x98, 0xf1, 0x90, 0xc8, 0x7e, 0x4d, 0x2f, 0x91, 0x96, 0x96, 0x09, 0xd5, 0xfe, 0x94, 0xa2, 0x4e,
	0x92, 0xaf, 0x2b, 0xc4, 0x8c, 0xe3, 0xc7, 0x1c, 0x29, 0xb2, 0x1c, 0xd8, 0xdf, 0x60, 0xfe, 0x35,
	0x3a, 0x83, 0x62, 0x20, 0x43, 0x91, 0xa9, 0xca, 0xc3, 0xee, 0xe5, 0xac, 0xce, 0x53, 0x4d, 0xfb,
	0x4b, 0x01, 0x23, 0x63, 0xc0, 0xae, 0x40, 0x5f, 0xad, 0xc5, 0xf2, 0x5a, 0x6b, 0x87, 0x6b, 0xe0,
	0xe6, 0x0d, 0x9e, 0x60, 0xf7, 0x47, 0x6a, 0x76, 0xbc, 0xd6, 0x92, 0xbf, 0x6d, 0xed, 0xe4, 0x6f,
	0x51, 0x32, 0xdd, 0xd1, 0xe4, 0x8f, 0xbc, 0xf8, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x10, 0x29,
	0x8a, 0xa6, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AddressBookClient is the client API for AddressBook service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddressBookClient interface {
	AddPerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*AddPersonResponse, error)
	ListAddressBook(ctx context.Context, in *ListAddressBookRequest, opts ...grpc.CallOption) (*ListAddressBookResponse, error)
}

type addressBookClient struct {
	cc *grpc.ClientConn
}

func NewAddressBookClient(cc *grpc.ClientConn) AddressBookClient {
	return &addressBookClient{cc}
}

func (c *addressBookClient) AddPerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*AddPersonResponse, error) {
	out := new(AddPersonResponse)
	err := c.cc.Invoke(ctx, "/addressbook.AddressBook/AddPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressBookClient) ListAddressBook(ctx context.Context, in *ListAddressBookRequest, opts ...grpc.CallOption) (*ListAddressBookResponse, error) {
	out := new(ListAddressBookResponse)
	err := c.cc.Invoke(ctx, "/addressbook.AddressBook/ListAddressBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddressBookServer is the server API for AddressBook service.
type AddressBookServer interface {
	AddPerson(context.Context, *Person) (*AddPersonResponse, error)
	ListAddressBook(context.Context, *ListAddressBookRequest) (*ListAddressBookResponse, error)
}

// UnimplementedAddressBookServer can be embedded to have forward compatible implementations.
type UnimplementedAddressBookServer struct {
}

func (*UnimplementedAddressBookServer) AddPerson(ctx context.Context, req *Person) (*AddPersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPerson not implemented")
}
func (*UnimplementedAddressBookServer) ListAddressBook(ctx context.Context, req *ListAddressBookRequest) (*ListAddressBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAddressBook not implemented")
}

func RegisterAddressBookServer(s *grpc.Server, srv AddressBookServer) {
	s.RegisterService(&_AddressBook_serviceDesc, srv)
}

func _AddressBook_AddPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressBookServer).AddPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/addressbook.AddressBook/AddPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressBookServer).AddPerson(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressBook_ListAddressBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAddressBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressBookServer).ListAddressBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/addressbook.AddressBook/ListAddressBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressBookServer).ListAddressBook(ctx, req.(*ListAddressBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddressBook_serviceDesc = grpc.ServiceDesc{
	ServiceName: "addressbook.AddressBook",
	HandlerType: (*AddressBookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPerson",
			Handler:    _AddressBook_AddPerson_Handler,
		},
		{
			MethodName: "ListAddressBook",
			Handler:    _AddressBook_ListAddressBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "addressbook.proto",
}
